spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  cache:
    type: redis
    cache-names: idemp
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password  # 필요 시 주석 해제
  h2:
    console:
      enabled: true

jwt:
  secret: dev-jwt-secret-key-for-development-only-very-long-secret-key
  access-token-expiration: 3600000  # 1시간 (밀리초)
  refresh-token-expiration: 2592000000  # 30일 (밀리초)

logging:
  level:
    com.ipia.order: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
