name: 기타/작업 (Chore)
description: 리팩토링, 빌드/CI, 문서화 등 운영성 작업 이슈
title: "[Chore] "
labels: ["chore"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: 작업 개요
      description: 목적과 배경을 간단히 설명해주세요.
      placeholder: 예) Gradle 캐시 최적화, 린트 규칙 정비 등
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: 해야 할 일
      description: 구체적인 작업 항목을 나열해주세요.
      placeholder: "- [ ] ...\n- [ ] ..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 영향 범위
      description: 코드/빌드/문서 등 영향 구역을 적어주세요.
  - type: textarea
    id: etc
    attributes:
      label: 비고
      description: 추가로 공유할 내용을 작성해주세요.


