name: 서브 이슈 (Sub-task)
description: 상위 이슈를 쪼개는 하위 작업 이슈 템플릿
title: "[Sub] "
labels: ["subtask"]
assignees: []
body:
  - type: input
    id: parent
    attributes:
      label: 상위 이슈 링크
      description: 상위(메인) 이슈의 링크 또는 번호를 입력해주세요. (예: #123)
      placeholder: #123
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 배경/맥락
      description: 왜 이 서브 이슈가 필요한지 간단히 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 작업 범위
      description: 구체적으로 무엇을 할지, 범위를 명확히 적어주세요.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 완료 기준 (Acceptance Criteria)
      description: 완료로 판단할 수 있는 검증 가능한 조건을 나열해주세요.
      placeholder: "- [ ] API 응답에 필드 A 포함\n- [ ] 예외 케이스 B 처리"
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Task List
      description: 필요한 세부 작업을 체크리스트로 작성해주세요.
      placeholder: "- [ ] 단위 테스트 작성\n- [ ] 최소 구현\n- [ ] 코드 리뷰 반영"

  - type: input
    id: dependencies
    attributes:
      label: 선행/연관 이슈
      description: 선행되어야 하거나 연관된 이슈가 있다면 번호를 적어주세요. (예: #120, #121)

  - type: dropdown
    id: estimate
    attributes:
      label: 예상 난이도/규모
      description: 대략적인 규모를 선택해주세요.
      options:
        - XS
        - S
        - M
        - L
        - XL
    validations:
      required: false

